version: '3.4'

services:
  v2rayapi:
    image: v2rayapi:dev
    container_name: V2Ray.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "V2Ray.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_v2rayapi$
    volumes:
      - C:\Repos\OutlineVpn\V2Ray.Api:/app
      - C:\Repos\OutlineVpn:/src
      - C:\Users\Mostafa\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_v2rayapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_v2rayapi$ \"/app/bin/Debug/net6.0/V2Ray.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true